/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    industries: Industry;
    services: Service;
    partners: Partner;
    articles: Article;
    caseStudies: CaseStudy;
    testimonials: Testimonial;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    caseStudies: CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    siteSettings: SiteSetting;
    header: Header;
    footer: Footer;
    homePage: HomePage;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    homePage: HomePageSelect<false> | HomePageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for accessibility and SEO.
   */
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  title: string;
  /**
   * lucide icon name, e.g. "train-front", "bot", "cog".
   */
  icon: string;
  /**
   * Sort order (low → first).
   */
  order?: number | null;
  /**
   * URL segment. Lowercase, hyphenated. Derived from "title" if left blank.
   */
  slug: string;
  /**
   * One-line summary used on the Home tab and Consulting grid.
   */
  shortDescription: string;
  /**
   * Capability bullet points shown on the Home tab.
   */
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Applicable standards (chips).
   */
  standards?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  hero?: {
    headline?: string | null;
    intro?: string | null;
  };
  capabilities?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  experienceHighlight?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * lucide icon name, e.g. "wrench", "compass".
   */
  icon: string;
  order?: number | null;
  description: string;
  points?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  bestFor?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  type: 'customer' | 'partner';
  order?: number | null;
  /**
   * e.g. "deere.com" — used to fetch the brand icon.
   */
  domain?: string | null;
  /**
   * Shown if the icon fails to load, e.g. "JD".
   */
  mono?: string | null;
  /**
   * Partner role, e.g. "Certification Partner". (Partners only.)
   */
  role?: string | null;
  /**
   * Optional outbound link.
   */
  url?: string | null;
  /**
   * Optional uploaded logo (overrides the icon service).
   */
  logo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * URL segment. Lowercase, hyphenated. Derived from "title" if left blank.
   */
  slug: string;
  /**
   * e.g. "Standards", "Field Notes", "Company".
   */
  category: string;
  publishedDate: string;
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "caseStudies".
 */
export interface CaseStudy {
  id: number;
  name: string;
  sector: string;
  order?: number | null;
  description: string;
  standards?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  coverImage?: (number | null) | Media;
  testimonial?: {
    quote?: string | null;
    author?: string | null;
    affiliation?: string | null;
  };
  problem?: string | null;
  solution?: string | null;
  result?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  attribution: string;
  company?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'caseStudies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  title?: T;
  icon?: T;
  order?: T;
  slug?: T;
  shortDescription?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  standards?:
    | T
    | {
        label?: T;
        id?: T;
      };
  hero?:
    | T
    | {
        headline?: T;
        intro?: T;
      };
  capabilities?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  experienceHighlight?: T;
  ctaLabel?: T;
  ctaHref?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  icon?: T;
  order?: T;
  description?: T;
  points?:
    | T
    | {
        text?: T;
        id?: T;
      };
  bestFor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  order?: T;
  domain?: T;
  mono?: T;
  role?: T;
  url?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  publishedDate?: T;
  excerpt?: T;
  heroImage?: T;
  body?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "caseStudies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  name?: T;
  sector?: T;
  order?: T;
  description?: T;
  standards?:
    | T
    | {
        label?: T;
        id?: T;
      };
  coverImage?: T;
  testimonial?:
    | T
    | {
        quote?: T;
        author?: T;
        affiliation?: T;
      };
  problem?: T;
  solution?: T;
  result?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  attribution?: T;
  company?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * White logo used in the nav and footer.
   */
  logo?: (number | null) | Media;
  defaultSeo?: {
    title?: string | null;
    description?: string | null;
  };
  social?: {
    linkedin?: string | null;
    x?: string | null;
    youtube?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  nav?:
    | {
        label: string;
        href: string;
        children?:
          | {
              label: string;
              href: string;
              isCTA?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  utility?: {
    loginLabel?: string | null;
    loginHref?: string | null;
    cartHref?: string | null;
    consultationLabel?: string | null;
    consultationHref?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  closingCta?: {
    eyebrow?: string | null;
    /**
     * Use a line break for two lines.
     */
    title?: string | null;
    sub?: string | null;
    primaryLabel?: string | null;
    primaryHref?: string | null;
    secondaryLabel?: string | null;
    secondaryHref?: string | null;
  };
  brandBlurb?: string | null;
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage".
 */
export interface HomePage {
  id: number;
  hero?: {
    titleLine1?: string | null;
    titleLine2?: string | null;
    /**
     * Word within line 2 rendered with the gold shimmer.
     */
    highlightWord?: string | null;
    subhead?: string | null;
    sub?: string | null;
    primaryCtaLabel?: string | null;
    primaryCtaHref?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
    /**
     * Full-bleed background video.
     */
    backgroundVideoUrl?: string | null;
    /**
     * The rotating safety-critical systems in the hero.
     */
    systems?:
      | {
          category: string;
          name: string;
          blurb: string;
          /**
           * e.g. /assets/sys-1.webm
           */
          videoUrl?: string | null;
          /**
           * e.g. /assets/sys-1-fit.png
           */
          posterUrl?: string | null;
          isGif?: boolean | null;
          metricLabel?: string | null;
          metricValue?: string | null;
          standards?:
            | {
                label: string;
                id?: string | null;
              }[]
            | null;
          sizeK?: number | null;
          offsetY?: number | null;
          activeRY?: number | null;
          id?: string | null;
        }[]
      | null;
    tickerStandards?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  problem?: {
    eyebrow?: string | null;
    title?: string | null;
    lead?: string | null;
    solutionLabel?: string | null;
    solutions?:
      | {
          icon: string;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Cards come from the Services and Industries collections.
   */
  servicesSection?: {
    eyebrow?: string | null;
    servicesTitle?: string | null;
    industriesTitle?: string | null;
    servicesLead?: string | null;
    industriesLead?: string | null;
    servicesCta?: string | null;
    industriesCta?: string | null;
  };
  standingApart?: {
    eyebrow?: string | null;
    title?: string | null;
    lead?: string | null;
    mandateKicker?: string | null;
    mandateTag?: string | null;
    oldWayLabel?: string | null;
    newWayLabel?: string | null;
    rows?:
      | {
          theme: string;
          oldTitle: string;
          newTitle: string;
          oldDesc: string;
          newDesc: string;
          id?: string | null;
        }[]
      | null;
    neverAiLabel?: string | null;
    neverAi?:
      | {
          icon: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    humanNote?: string | null;
  };
  about?: {
    eyebrow?: string | null;
    title?: string | null;
    portrait?: (number | null) | Media;
    name?: string | null;
    role?: string | null;
    location?: string | null;
    calloutLabel?: string | null;
    /**
     * Founder biography (supports bold).
     */
    bio?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    certs?:
      | {
          icon: string;
          title: string;
          subtitle: string;
          id?: string | null;
        }[]
      | null;
    experienceLabel?: string | null;
    experienceTags?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    activeLabel?: string | null;
    activeNote?: string | null;
    conferences?:
      | {
          icon: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  caseStudiesSection?: {
    eyebrow?: string | null;
    title?: string | null;
    sub?: string | null;
    ctaLabel?: string | null;
  };
  partnersSection?: {
    eyebrow?: string | null;
    title?: string | null;
    sub?: string | null;
    partnersLabel?: string | null;
    partnersIntro?: string | null;
  };
  newsSection?: {
    eyebrow?: string | null;
    title?: string | null;
    lead?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  social?:
    | T
    | {
        linkedin?: T;
        x?: T;
        youtube?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  nav?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              isCTA?: T;
              id?: T;
            };
        id?: T;
      };
  utility?:
    | T
    | {
        loginLabel?: T;
        loginHref?: T;
        cartHref?: T;
        consultationLabel?: T;
        consultationHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  closingCta?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
        primaryLabel?: T;
        primaryHref?: T;
        secondaryLabel?: T;
        secondaryHref?: T;
      };
  brandBlurb?: T;
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        titleLine1?: T;
        titleLine2?: T;
        highlightWord?: T;
        subhead?: T;
        sub?: T;
        primaryCtaLabel?: T;
        primaryCtaHref?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
        backgroundVideoUrl?: T;
        systems?:
          | T
          | {
              category?: T;
              name?: T;
              blurb?: T;
              videoUrl?: T;
              posterUrl?: T;
              isGif?: T;
              metricLabel?: T;
              metricValue?: T;
              standards?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              sizeK?: T;
              offsetY?: T;
              activeRY?: T;
              id?: T;
            };
        tickerStandards?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  problem?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        solutionLabel?: T;
        solutions?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  servicesSection?:
    | T
    | {
        eyebrow?: T;
        servicesTitle?: T;
        industriesTitle?: T;
        servicesLead?: T;
        industriesLead?: T;
        servicesCta?: T;
        industriesCta?: T;
      };
  standingApart?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        mandateKicker?: T;
        mandateTag?: T;
        oldWayLabel?: T;
        newWayLabel?: T;
        rows?:
          | T
          | {
              theme?: T;
              oldTitle?: T;
              newTitle?: T;
              oldDesc?: T;
              newDesc?: T;
              id?: T;
            };
        neverAiLabel?: T;
        neverAi?:
          | T
          | {
              icon?: T;
              label?: T;
              id?: T;
            };
        humanNote?: T;
      };
  about?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        portrait?: T;
        name?: T;
        role?: T;
        location?: T;
        calloutLabel?: T;
        bio?: T;
        certs?:
          | T
          | {
              icon?: T;
              title?: T;
              subtitle?: T;
              id?: T;
            };
        experienceLabel?: T;
        experienceTags?:
          | T
          | {
              label?: T;
              id?: T;
            };
        activeLabel?: T;
        activeNote?: T;
        conferences?:
          | T
          | {
              icon?: T;
              label?: T;
              id?: T;
            };
        ctaLabel?: T;
        ctaHref?: T;
      };
  caseStudiesSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
        ctaLabel?: T;
      };
  partnersSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
        partnersLabel?: T;
        partnersIntro?: T;
      };
  newsSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}