/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    industries: Industry;
    services: Service;
    customers: Customer;
    partners: Partner;
    articles: Article;
    caseStudies: CaseStudy;
    testimonials: Testimonial;
    templates: Template;
    courses: Course;
    resources: Resource;
    events: Event;
    freeTrainings: FreeTraining;
    teamMembers: TeamMember;
    jobPostings: JobPosting;
    legalPages: LegalPage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    caseStudies: CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    templates: TemplatesSelect<false> | TemplatesSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    freeTrainings: FreeTrainingsSelect<false> | FreeTrainingsSelect<true>;
    teamMembers: TeamMembersSelect<false> | TeamMembersSelect<true>;
    jobPostings: JobPostingsSelect<false> | JobPostingsSelect<true>;
    legalPages: LegalPagesSelect<false> | LegalPagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    siteSettings: SiteSetting;
    header: Header;
    footer: Footer;
    homePage: HomePage;
    consultingOverview: ConsultingOverview;
    trainingTemplatesOverview: TrainingTemplatesOverview;
    companyAbout: CompanyAbout;
    companyServices: CompanyService;
    companyExperience: CompanyExperience;
    careersIntro: CareersIntro;
    resourcesOverview: ResourcesOverview;
    standardsIdentifierPage: StandardsIdentifierPage;
    safetyChatPage: SafetyChatPage;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    homePage: HomePageSelect<false> | HomePageSelect<true>;
    consultingOverview: ConsultingOverviewSelect<false> | ConsultingOverviewSelect<true>;
    trainingTemplatesOverview: TrainingTemplatesOverviewSelect<false> | TrainingTemplatesOverviewSelect<true>;
    companyAbout: CompanyAboutSelect<false> | CompanyAboutSelect<true>;
    companyServices: CompanyServicesSelect<false> | CompanyServicesSelect<true>;
    companyExperience: CompanyExperienceSelect<false> | CompanyExperienceSelect<true>;
    careersIntro: CareersIntroSelect<false> | CareersIntroSelect<true>;
    resourcesOverview: ResourcesOverviewSelect<false> | ResourcesOverviewSelect<true>;
    standardsIdentifierPage: StandardsIdentifierPageSelect<false> | StandardsIdentifierPageSelect<true>;
    safetyChatPage: SafetyChatPageSelect<false> | SafetyChatPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for accessibility and SEO.
   */
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  title: string;
  /**
   * lucide icon name, e.g. "train-front", "bot", "cog".
   */
  icon: string;
  /**
   * Sort order (low → first).
   */
  order?: number | null;
  /**
   * URL segment. Lowercase, hyphenated. Derived from "title" if left blank.
   */
  slug: string;
  /**
   * One-line summary used on the Home tab and Consulting grid.
   */
  shortDescription: string;
  /**
   * Capability bullet points shown on the Home tab.
   */
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Applicable standards (chips).
   */
  standards?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  hero?: {
    headline?: string | null;
    intro?: string | null;
  };
  capabilities?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  experienceHighlight?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * lucide icon name, e.g. "wrench", "compass".
   */
  icon: string;
  order?: number | null;
  description: string;
  points?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  bestFor?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  name: string;
  order?: number | null;
  /**
   * e.g. "deere.com" — used to fetch the brand icon.
   */
  domain?: string | null;
  /**
   * Shown if the icon fails to load, e.g. "JD".
   */
  mono?: string | null;
  /**
   * Optional outbound link.
   */
  url?: string | null;
  /**
   * Optional uploaded logo (overrides the icon service).
   */
  logo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  order?: number | null;
  /**
   * e.g. "Certification Partner", "Technical Collaboration".
   */
  role?: string | null;
  /**
   * e.g. "tuv.com" — used to fetch the brand icon.
   */
  domain?: string | null;
  /**
   * Shown if the icon fails to load, e.g. "TÜV".
   */
  mono?: string | null;
  /**
   * Optional outbound link.
   */
  url?: string | null;
  /**
   * Optional uploaded logo (overrides the icon service).
   */
  logo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * URL segment. Lowercase, hyphenated. Derived from "title" if left blank.
   */
  slug: string;
  /**
   * e.g. "Standards", "Field Notes", "Company".
   */
  category: string;
  publishedDate: string;
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "caseStudies".
 */
export interface CaseStudy {
  id: number;
  name: string;
  sector: string;
  order?: number | null;
  description: string;
  standards?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  coverImage?: (number | null) | Media;
  testimonial?: {
    quote?: string | null;
    author?: string | null;
    affiliation?: string | null;
  };
  problem?: string | null;
  solution?: string | null;
  result?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  attribution: string;
  company?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates".
 */
export interface Template {
  id: number;
  title: string;
  order?: number | null;
  /**
   * URL segment. Lowercase, hyphenated. Derived from "title" if left blank.
   */
  slug: string;
  description: string;
  category: 'compliance-bundle' | 'qms' | 'fs';
  format?: ('word' | 'excel') | null;
  /**
   * e.g. "ISO 26262", "IEC 61508".
   */
  standardFocus?: string | null;
  /**
   * e.g. "Plan", "Checklist", "Report template".
   */
  documentType?: string | null;
  /**
   * Placeholder price (no checkout in Phase 1), e.g. "$149".
   */
  price?: string | null;
  thumbnail?: (number | null) | Media;
  whatsIncluded?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Mark bundles so the storefront can group them.
   */
  isBundle?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  order?: number | null;
  /**
   * URL segment. Lowercase, hyphenated. Derived from "title" if left blank.
   */
  slug: string;
  summary: string;
  /**
   * Track or industry, e.g. "Rail", "Robotics".
   */
  track?: string | null;
  format?: ('online' | 'in-person' | 'hybrid' | 'self-paced') | null;
  /**
   * e.g. "Certificate of completion".
   */
  credential?: string | null;
  /**
   * Placeholder price (no checkout in Phase 1).
   */
  price?: string | null;
  instructor?: string | null;
  media?: (number | null) | Media;
  modules?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  title: string;
  category: 'checklist' | 'guidebook' | 'free-template' | 'standards-guide';
  order?: number | null;
  description: string;
  /**
   * The downloadable file (PDF, Word, Excel).
   */
  file?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  type: 'upcoming' | 'past-keynote' | 'webinar';
  date?: string | null;
  description?: string | null;
  /**
   * Registration or recording link.
   */
  link?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "freeTrainings".
 */
export interface FreeTraining {
  id: number;
  title: string;
  category: 'video-overview' | 'whitepaper' | 'core-intro';
  order?: number | null;
  description: string;
  media?: (number | null) | Media;
  /**
   * External video/whitepaper link, if any.
   */
  link?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teamMembers".
 */
export interface TeamMember {
  id: number;
  name: string;
  role: string;
  order?: number | null;
  photo?: (number | null) | Media;
  bio?: string | null;
  credentials?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  location?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobPostings".
 */
export interface JobPosting {
  id: number;
  title: string;
  location?: string | null;
  order?: number | null;
  summary: string;
  applyLink?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legalPages".
 */
export interface LegalPage {
  id: number;
  title: string;
  /**
   * URL segment. Lowercase, hyphenated. Derived from "title" if left blank.
   */
  slug: string;
  lastUpdated?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'caseStudies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'templates';
        value: number | Template;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'freeTrainings';
        value: number | FreeTraining;
      } | null)
    | ({
        relationTo: 'teamMembers';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'jobPostings';
        value: number | JobPosting;
      } | null)
    | ({
        relationTo: 'legalPages';
        value: number | LegalPage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  title?: T;
  icon?: T;
  order?: T;
  slug?: T;
  shortDescription?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  standards?:
    | T
    | {
        label?: T;
        id?: T;
      };
  hero?:
    | T
    | {
        headline?: T;
        intro?: T;
      };
  capabilities?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  experienceHighlight?: T;
  ctaLabel?: T;
  ctaHref?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  icon?: T;
  order?: T;
  description?: T;
  points?:
    | T
    | {
        text?: T;
        id?: T;
      };
  bestFor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  order?: T;
  domain?: T;
  mono?: T;
  url?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  order?: T;
  role?: T;
  domain?: T;
  mono?: T;
  url?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  publishedDate?: T;
  excerpt?: T;
  heroImage?: T;
  body?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "caseStudies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  name?: T;
  sector?: T;
  order?: T;
  description?: T;
  standards?:
    | T
    | {
        label?: T;
        id?: T;
      };
  coverImage?: T;
  testimonial?:
    | T
    | {
        quote?: T;
        author?: T;
        affiliation?: T;
      };
  problem?: T;
  solution?: T;
  result?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  attribution?: T;
  company?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates_select".
 */
export interface TemplatesSelect<T extends boolean = true> {
  title?: T;
  order?: T;
  slug?: T;
  description?: T;
  category?: T;
  format?: T;
  standardFocus?: T;
  documentType?: T;
  price?: T;
  thumbnail?: T;
  whatsIncluded?:
    | T
    | {
        text?: T;
        id?: T;
      };
  isBundle?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  order?: T;
  slug?: T;
  summary?: T;
  track?: T;
  format?: T;
  credential?: T;
  price?: T;
  instructor?: T;
  media?: T;
  modules?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  order?: T;
  description?: T;
  file?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  date?: T;
  description?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "freeTrainings_select".
 */
export interface FreeTrainingsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  order?: T;
  description?: T;
  media?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teamMembers_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  order?: T;
  photo?: T;
  bio?: T;
  credentials?:
    | T
    | {
        label?: T;
        id?: T;
      };
  location?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobPostings_select".
 */
export interface JobPostingsSelect<T extends boolean = true> {
  title?: T;
  location?: T;
  order?: T;
  summary?: T;
  applyLink?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legalPages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  lastUpdated?: T;
  body?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * White logo used in the nav and footer.
   */
  logo?: (number | null) | Media;
  defaultSeo?: {
    title?: string | null;
    description?: string | null;
  };
  social?: {
    linkedin?: string | null;
    x?: string | null;
    youtube?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  nav?:
    | {
        label: string;
        href: string;
        children?:
          | {
              label: string;
              href: string;
              isCTA?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  utility?: {
    loginLabel?: string | null;
    loginHref?: string | null;
    cartHref?: string | null;
    consultationLabel?: string | null;
    consultationHref?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  closingCta?: {
    eyebrow?: string | null;
    /**
     * Use a line break for two lines.
     */
    title?: string | null;
    sub?: string | null;
    primaryLabel?: string | null;
    primaryHref?: string | null;
    secondaryLabel?: string | null;
    secondaryHref?: string | null;
  };
  brandBlurb?: string | null;
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage".
 */
export interface HomePage {
  id: number;
  hero?: {
    titleLine1?: string | null;
    titleLine2?: string | null;
    /**
     * Word within line 2 rendered with the gold shimmer.
     */
    highlightWord?: string | null;
    subhead?: string | null;
    sub?: string | null;
    primaryCtaLabel?: string | null;
    primaryCtaHref?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
    /**
     * Full-bleed background video.
     */
    backgroundVideoUrl?: string | null;
    /**
     * The rotating safety-critical systems in the hero.
     */
    systems?:
      | {
          category: string;
          name: string;
          blurb: string;
          /**
           * e.g. /assets/sys-1.webm
           */
          videoUrl?: string | null;
          /**
           * e.g. /assets/sys-1-fit.png
           */
          posterUrl?: string | null;
          isGif?: boolean | null;
          metricLabel?: string | null;
          metricValue?: string | null;
          standards?:
            | {
                label: string;
                id?: string | null;
              }[]
            | null;
          sizeK?: number | null;
          offsetY?: number | null;
          activeRY?: number | null;
          id?: string | null;
        }[]
      | null;
    tickerStandards?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  problem?: {
    eyebrow?: string | null;
    title?: string | null;
    lead?: string | null;
    solutionLabel?: string | null;
    solutions?:
      | {
          icon: string;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Cards come from the Services and Industries collections.
   */
  servicesSection?: {
    eyebrow?: string | null;
    servicesTitle?: string | null;
    industriesTitle?: string | null;
    servicesLead?: string | null;
    industriesLead?: string | null;
    servicesCta?: string | null;
    industriesCta?: string | null;
  };
  standingApart?: {
    eyebrow?: string | null;
    title?: string | null;
    lead?: string | null;
    mandateKicker?: string | null;
    mandateTag?: string | null;
    oldWayLabel?: string | null;
    newWayLabel?: string | null;
    rows?:
      | {
          theme: string;
          oldTitle: string;
          newTitle: string;
          oldDesc: string;
          newDesc: string;
          id?: string | null;
        }[]
      | null;
    neverAiLabel?: string | null;
    neverAi?:
      | {
          icon: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    humanNote?: string | null;
  };
  about?: {
    eyebrow?: string | null;
    title?: string | null;
    portrait?: (number | null) | Media;
    name?: string | null;
    role?: string | null;
    location?: string | null;
    calloutLabel?: string | null;
    /**
     * Founder biography (supports bold).
     */
    bio?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    certs?:
      | {
          icon: string;
          title: string;
          subtitle: string;
          id?: string | null;
        }[]
      | null;
    experienceLabel?: string | null;
    experienceTags?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    activeLabel?: string | null;
    activeNote?: string | null;
    conferences?:
      | {
          icon: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  caseStudiesSection?: {
    eyebrow?: string | null;
    title?: string | null;
    sub?: string | null;
    ctaLabel?: string | null;
  };
  partnersSection?: {
    eyebrow?: string | null;
    title?: string | null;
    sub?: string | null;
    partnersLabel?: string | null;
    partnersIntro?: string | null;
  };
  newsSection?: {
    eyebrow?: string | null;
    title?: string | null;
    lead?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultingOverview".
 */
export interface ConsultingOverview {
  id: number;
  hero?: {
    eyebrow?: string | null;
    /**
     * Large background watermark word.
     */
    ghost?: string | null;
    /**
     * Supports a line break (\n) for the two-line display.
     */
    title?: string | null;
    sub?: string | null;
    primaryCtaLabel?: string | null;
    primaryCtaHref?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
    standards?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    hud?: {
      tag?: string | null;
      badge?: string | null;
      foot?: string | null;
      steps?:
        | {
            title: string;
            description: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  facts?: {
    eyebrow?: string | null;
    title?: string | null;
    lead?: string | null;
    items?:
      | {
          icon: string;
          kicker: string;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  about?: {
    eyebrow?: string | null;
    title?: string | null;
    /**
     * Lead paragraph (supports bold).
     */
    prose?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    quote?: string | null;
    credsLabel?: string | null;
    creds?:
      | {
          icon: string;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  options?: {
    eyebrow?: string | null;
    title?: string | null;
    lead?: string | null;
    items?:
      | {
          /**
           * e.g. "Option 01".
           */
          number: string;
          icon: string;
          title: string;
          description: string;
          bestFor?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  capabilities?: {
    eyebrow?: string | null;
    title?: string | null;
    lead?: string | null;
    items?:
      | {
          icon: string;
          code: string;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Cards come from the Industries collection.
   */
  industriesSection?: {
    eyebrow?: string | null;
    title?: string | null;
    lead?: string | null;
  };
  faq?: {
    eyebrow?: string | null;
    title?: string | null;
    items?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  closing?: {
    eyebrow?: string | null;
    title?: string | null;
    sub?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trainingTemplatesOverview".
 */
export interface TrainingTemplatesOverview {
  id: number;
  overviewHero?: {
    /**
     * Breadcrumb current-page label.
     */
    crumb?: string | null;
    /**
     * Large background watermark word.
     */
    ghost?: string | null;
    /**
     * Supports a line break (\n) for the two-line display.
     */
    title?: string | null;
    lead?: string | null;
    primaryCtaLabel?: string | null;
    primaryCtaHref?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
    standards?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  ways?: {
    eyebrow?: string | null;
    title?: string | null;
    lead?: string | null;
    items?:
      | {
          /**
           * e.g. "01".
           */
          num: string;
          icon: string;
          title: string;
          description: string;
          meta?:
            | {
                label: string;
                id?: string | null;
              }[]
            | null;
          ctaLabel: string;
          ctaHref: string;
          id?: string | null;
        }[]
      | null;
  };
  coursesHero?: {
    crumb?: string | null;
    ghost?: string | null;
    /**
     * Supports a line break (\n).
     */
    title?: string | null;
    lead?: string | null;
    primaryCtaLabel?: string | null;
    primaryCtaHref?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
  };
  why?: {
    eyebrow?: string | null;
    title?: string | null;
    items?:
      | {
          icon: string;
          title: string;
          body: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Course cards come from the Courses collection.
   */
  catalog?: {
    eyebrow?: string | null;
    title?: string | null;
    lead?: string | null;
  };
  offerings?: {
    eyebrow?: string | null;
    title?: string | null;
    items?:
      | {
          num: string;
          title: string;
          body: string;
          badge: string;
          meta: string;
          id?: string | null;
        }[]
      | null;
  };
  coursesPrivate?: {
    eyebrow?: string | null;
    title?: string | null;
    sub?: string | null;
    primaryLabel?: string | null;
    primaryHref?: string | null;
    secondaryLabel?: string | null;
    secondaryHref?: string | null;
  };
  templatesHero?: {
    crumb?: string | null;
    ghost?: string | null;
    /**
     * Supports a line break (\n).
     */
    title?: string | null;
    lead?: string | null;
    primaryCtaLabel?: string | null;
    primaryCtaHref?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
    standards?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  featured?: {
    badge?: string | null;
    icon?: string | null;
    tag?: string | null;
    title?: string | null;
    description?: string | null;
    chips?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    priceMeta?: string | null;
    primaryLabel?: string | null;
    secondaryLabel?: string | null;
  };
  /**
   * Template products & bundles come from the Templates collection.
   */
  store?: {
    eyebrow?: string | null;
    title?: string | null;
    lead?: string | null;
    pricingNote?: string | null;
  };
  templatesClosing?: {
    eyebrow?: string | null;
    title?: string | null;
    sub?: string | null;
    stats?:
      | {
          /**
           * Bold figure, e.g. "4". Leave blank for a plain label.
           */
          value?: string | null;
          label: string;
          id?: string | null;
        }[]
      | null;
    primaryLabel?: string | null;
    primaryHref?: string | null;
    secondaryLabel?: string | null;
    secondaryHref?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companyAbout".
 */
export interface CompanyAbout {
  id: number;
  hero?: {
    ghost?: string | null;
    icon?: string | null;
    eyebrow?: string | null;
    title?: string | null;
    tagline?: string | null;
    intro?: string | null;
    primaryCtaLabel?: string | null;
    primaryCtaHref?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
    hud?: {
      tag?: string | null;
      badge?: string | null;
      foot?: string | null;
      rows?:
        | {
            icon: string;
            t: string;
            d?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  mission?: {
    num?: string | null;
    eyebrow?: string | null;
    title?: string | null;
    /**
     * Mission prose (supports bold/italic).
     */
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  philosophy?: {
    num?: string | null;
    eyebrow?: string | null;
    title?: string | null;
    /**
     * Philosophy prose (supports bold).
     */
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    boundary?: {
      icon?: string | null;
      title?: string | null;
      /**
       * Boundary detail (supports bold).
       */
      body?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
    };
  };
  values?: {
    eyebrow?: string | null;
    title?: string | null;
    lead?: string | null;
    items?:
      | {
          icon: string;
          t: string;
          d: string;
          id?: string | null;
        }[]
      | null;
  };
  iso?: {
    icon?: string | null;
    eyebrow?: string | null;
    /**
     * ISO panel prose (supports bold).
     */
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  closing?: {
    eyebrow?: string | null;
    title?: string | null;
    sub?: string | null;
    primaryLabel?: string | null;
    primaryHref?: string | null;
    secondaryLabel?: string | null;
    secondaryHref?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companyServices".
 */
export interface CompanyService {
  id: number;
  hero?: {
    ghost?: string | null;
    icon?: string | null;
    eyebrow?: string | null;
    title?: string | null;
    tagline?: string | null;
    intro?: string | null;
    standards?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    primaryCtaLabel?: string | null;
    primaryCtaHref?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
    hud?: {
      tag?: string | null;
      badge?: string | null;
      foot?: string | null;
      rows?:
        | {
            icon: string;
            t: string;
            d?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  models?: {
    eyebrow?: string | null;
    title?: string | null;
    lead?: string | null;
    items?:
      | {
          icon: string;
          t: string;
          d: string;
          best: string;
          id?: string | null;
        }[]
      | null;
  };
  closing?: {
    eyebrow?: string | null;
    title?: string | null;
    sub?: string | null;
    primaryLabel?: string | null;
    primaryHref?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companyExperience".
 */
export interface CompanyExperience {
  id: number;
  hero?: {
    ghost?: string | null;
    icon?: string | null;
    eyebrow?: string | null;
    title?: string | null;
    tagline?: string | null;
    intro?: string | null;
    standards?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    primaryCtaLabel?: string | null;
    primaryCtaHref?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
    hud?: {
      tag?: string | null;
      badge?: string | null;
      foot?: string | null;
      rows?:
        | {
            icon: string;
            t: string;
            d?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  delivered?: {
    eyebrow?: string | null;
    title?: string | null;
    lead?: string | null;
    items?:
      | {
          icon: string;
          code: string;
          t: string;
          d: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Cards come from the Case Studies collection.
   */
  cases?: {
    eyebrow?: string | null;
    title?: string | null;
    lead?: string | null;
    note?: {
      icon?: string | null;
      bold?: string | null;
      text?: string | null;
    };
  };
  closing?: {
    eyebrow?: string | null;
    title?: string | null;
    sub?: string | null;
    primaryLabel?: string | null;
    primaryHref?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careersIntro".
 */
export interface CareersIntro {
  id: number;
  hero?: {
    ghost?: string | null;
    icon?: string | null;
    eyebrow?: string | null;
    title?: string | null;
    tagline?: string | null;
    intro?: string | null;
    primaryCtaLabel?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
    hud?: {
      tag?: string | null;
      badge?: string | null;
      foot?: string | null;
      rows?:
        | {
            icon: string;
            t: string;
            d?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  why?: {
    eyebrow?: string | null;
    title?: string | null;
    lead?: string | null;
    items?:
      | {
          icon: string;
          code: string;
          t: string;
          d: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Role cards come from the Job Postings collection.
   */
  roles?: {
    eyebrow?: string | null;
    title?: string | null;
    lead?: string | null;
    note?: {
      icon?: string | null;
      bold?: string | null;
      text?: string | null;
    };
  };
  closing?: {
    eyebrow?: string | null;
    title?: string | null;
    sub?: string | null;
    primaryLabel?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resourcesOverview".
 */
export interface ResourcesOverview {
  id: number;
  hero?: {
    eyebrow?: string | null;
    eyebrowIcon?: string | null;
    /**
     * Large background watermark word.
     */
    ghost?: string | null;
    title?: string | null;
    sub?: string | null;
    jump?:
      | {
          icon: string;
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  tools?: {
    eyebrow?: string | null;
    title?: string | null;
    lead?: string | null;
    items?:
      | {
          icon: string;
          tag: string;
          title: string;
          description: string;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  library?: {
    eyebrow?: string | null;
    title?: string | null;
    lead?: string | null;
    items?:
      | {
          icon: string;
          title: string;
          description: string;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  closing?: {
    eyebrow?: string | null;
    title?: string | null;
    sub?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "standardsIdentifierPage".
 */
export interface StandardsIdentifierPage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    eyebrowIcon?: string | null;
    /**
     * Large background watermark word.
     */
    ghost?: string | null;
    title?: string | null;
    sub1?: string | null;
    sub2?: string | null;
    primaryCtaLabel?: string | null;
    primaryCtaHref?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
  };
  /**
   * Phase 1: visual selection only — no live AI mapping.
   */
  tool?: {
    name?: string | null;
    sub?: string | null;
    badge?: string | null;
    selectors?:
      | {
          /**
           * e.g. "01".
           */
          step: string;
          label: string;
          options?:
            | {
                label: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    submitLabel?: string | null;
    submitNote?: string | null;
    resultLabel?: string | null;
    resultPreviewLabel?: string | null;
    roadmap?:
      | {
          code: string;
          pill: string;
          meta: string;
          id?: string | null;
        }[]
      | null;
    veilText?: string | null;
  };
  frameworks?: {
    eyebrow?: string | null;
    title?: string | null;
    lead?: string | null;
    items?:
      | {
          icon: string;
          title: string;
          codes?:
            | {
                label: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  howItWorks?: {
    eyebrow?: string | null;
    title?: string | null;
    steps?:
      | {
          number: string;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  closing?: {
    eyebrow?: string | null;
    title?: string | null;
    sub?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "safetyChatPage".
 */
export interface SafetyChatPage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    eyebrowIcon?: string | null;
    /**
     * Large background watermark word.
     */
    ghost?: string | null;
    title?: string | null;
    sub?: string | null;
    note?: string | null;
    primaryCtaLabel?: string | null;
    primaryCtaHref?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
  };
  /**
   * Phase 1: inert composer, no live model. Sample thread only.
   */
  panel?: {
    name?: string | null;
    status?: string | null;
    tag?: string | null;
    thread?:
      | {
          who: 'bot' | 'user';
          text: string;
          id?: string | null;
        }[]
      | null;
    suggestions?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    placeholder?: string | null;
    lockText?: string | null;
    lockCtaLabel?: string | null;
    lockCtaHref?: string | null;
  };
  closing?: {
    eyebrow?: string | null;
    title?: string | null;
    sub?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  social?:
    | T
    | {
        linkedin?: T;
        x?: T;
        youtube?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  nav?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              isCTA?: T;
              id?: T;
            };
        id?: T;
      };
  utility?:
    | T
    | {
        loginLabel?: T;
        loginHref?: T;
        cartHref?: T;
        consultationLabel?: T;
        consultationHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  closingCta?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
        primaryLabel?: T;
        primaryHref?: T;
        secondaryLabel?: T;
        secondaryHref?: T;
      };
  brandBlurb?: T;
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        titleLine1?: T;
        titleLine2?: T;
        highlightWord?: T;
        subhead?: T;
        sub?: T;
        primaryCtaLabel?: T;
        primaryCtaHref?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
        backgroundVideoUrl?: T;
        systems?:
          | T
          | {
              category?: T;
              name?: T;
              blurb?: T;
              videoUrl?: T;
              posterUrl?: T;
              isGif?: T;
              metricLabel?: T;
              metricValue?: T;
              standards?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              sizeK?: T;
              offsetY?: T;
              activeRY?: T;
              id?: T;
            };
        tickerStandards?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  problem?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        solutionLabel?: T;
        solutions?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  servicesSection?:
    | T
    | {
        eyebrow?: T;
        servicesTitle?: T;
        industriesTitle?: T;
        servicesLead?: T;
        industriesLead?: T;
        servicesCta?: T;
        industriesCta?: T;
      };
  standingApart?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        mandateKicker?: T;
        mandateTag?: T;
        oldWayLabel?: T;
        newWayLabel?: T;
        rows?:
          | T
          | {
              theme?: T;
              oldTitle?: T;
              newTitle?: T;
              oldDesc?: T;
              newDesc?: T;
              id?: T;
            };
        neverAiLabel?: T;
        neverAi?:
          | T
          | {
              icon?: T;
              label?: T;
              id?: T;
            };
        humanNote?: T;
      };
  about?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        portrait?: T;
        name?: T;
        role?: T;
        location?: T;
        calloutLabel?: T;
        bio?: T;
        certs?:
          | T
          | {
              icon?: T;
              title?: T;
              subtitle?: T;
              id?: T;
            };
        experienceLabel?: T;
        experienceTags?:
          | T
          | {
              label?: T;
              id?: T;
            };
        activeLabel?: T;
        activeNote?: T;
        conferences?:
          | T
          | {
              icon?: T;
              label?: T;
              id?: T;
            };
        ctaLabel?: T;
        ctaHref?: T;
      };
  caseStudiesSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
        ctaLabel?: T;
      };
  partnersSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
        partnersLabel?: T;
        partnersIntro?: T;
      };
  newsSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultingOverview_select".
 */
export interface ConsultingOverviewSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        ghost?: T;
        title?: T;
        sub?: T;
        primaryCtaLabel?: T;
        primaryCtaHref?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
        standards?:
          | T
          | {
              label?: T;
              id?: T;
            };
        hud?:
          | T
          | {
              tag?: T;
              badge?: T;
              foot?: T;
              steps?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
            };
      };
  facts?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        items?:
          | T
          | {
              icon?: T;
              kicker?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  about?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        prose?: T;
        quote?: T;
        credsLabel?: T;
        creds?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  options?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        items?:
          | T
          | {
              number?: T;
              icon?: T;
              title?: T;
              description?: T;
              bestFor?: T;
              id?: T;
            };
      };
  capabilities?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        items?:
          | T
          | {
              icon?: T;
              code?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  industriesSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
      };
  faq?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  closing?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trainingTemplatesOverview_select".
 */
export interface TrainingTemplatesOverviewSelect<T extends boolean = true> {
  overviewHero?:
    | T
    | {
        crumb?: T;
        ghost?: T;
        title?: T;
        lead?: T;
        primaryCtaLabel?: T;
        primaryCtaHref?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
        standards?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  ways?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        items?:
          | T
          | {
              num?: T;
              icon?: T;
              title?: T;
              description?: T;
              meta?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
            };
      };
  coursesHero?:
    | T
    | {
        crumb?: T;
        ghost?: T;
        title?: T;
        lead?: T;
        primaryCtaLabel?: T;
        primaryCtaHref?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
      };
  why?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              body?: T;
              id?: T;
            };
      };
  catalog?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
      };
  offerings?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        items?:
          | T
          | {
              num?: T;
              title?: T;
              body?: T;
              badge?: T;
              meta?: T;
              id?: T;
            };
      };
  coursesPrivate?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
        primaryLabel?: T;
        primaryHref?: T;
        secondaryLabel?: T;
        secondaryHref?: T;
      };
  templatesHero?:
    | T
    | {
        crumb?: T;
        ghost?: T;
        title?: T;
        lead?: T;
        primaryCtaLabel?: T;
        primaryCtaHref?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
        standards?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  featured?:
    | T
    | {
        badge?: T;
        icon?: T;
        tag?: T;
        title?: T;
        description?: T;
        chips?:
          | T
          | {
              label?: T;
              id?: T;
            };
        priceMeta?: T;
        primaryLabel?: T;
        secondaryLabel?: T;
      };
  store?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        pricingNote?: T;
      };
  templatesClosing?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        primaryLabel?: T;
        primaryHref?: T;
        secondaryLabel?: T;
        secondaryHref?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companyAbout_select".
 */
export interface CompanyAboutSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        ghost?: T;
        icon?: T;
        eyebrow?: T;
        title?: T;
        tagline?: T;
        intro?: T;
        primaryCtaLabel?: T;
        primaryCtaHref?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
        hud?:
          | T
          | {
              tag?: T;
              badge?: T;
              foot?: T;
              rows?:
                | T
                | {
                    icon?: T;
                    t?: T;
                    d?: T;
                    id?: T;
                  };
            };
      };
  mission?:
    | T
    | {
        num?: T;
        eyebrow?: T;
        title?: T;
        body?: T;
      };
  philosophy?:
    | T
    | {
        num?: T;
        eyebrow?: T;
        title?: T;
        body?: T;
        boundary?:
          | T
          | {
              icon?: T;
              title?: T;
              body?: T;
            };
      };
  values?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        items?:
          | T
          | {
              icon?: T;
              t?: T;
              d?: T;
              id?: T;
            };
      };
  iso?:
    | T
    | {
        icon?: T;
        eyebrow?: T;
        body?: T;
      };
  closing?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
        primaryLabel?: T;
        primaryHref?: T;
        secondaryLabel?: T;
        secondaryHref?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companyServices_select".
 */
export interface CompanyServicesSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        ghost?: T;
        icon?: T;
        eyebrow?: T;
        title?: T;
        tagline?: T;
        intro?: T;
        standards?:
          | T
          | {
              label?: T;
              id?: T;
            };
        primaryCtaLabel?: T;
        primaryCtaHref?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
        hud?:
          | T
          | {
              tag?: T;
              badge?: T;
              foot?: T;
              rows?:
                | T
                | {
                    icon?: T;
                    t?: T;
                    d?: T;
                    id?: T;
                  };
            };
      };
  models?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        items?:
          | T
          | {
              icon?: T;
              t?: T;
              d?: T;
              best?: T;
              id?: T;
            };
      };
  closing?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
        primaryLabel?: T;
        primaryHref?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companyExperience_select".
 */
export interface CompanyExperienceSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        ghost?: T;
        icon?: T;
        eyebrow?: T;
        title?: T;
        tagline?: T;
        intro?: T;
        standards?:
          | T
          | {
              label?: T;
              id?: T;
            };
        primaryCtaLabel?: T;
        primaryCtaHref?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
        hud?:
          | T
          | {
              tag?: T;
              badge?: T;
              foot?: T;
              rows?:
                | T
                | {
                    icon?: T;
                    t?: T;
                    d?: T;
                    id?: T;
                  };
            };
      };
  delivered?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        items?:
          | T
          | {
              icon?: T;
              code?: T;
              t?: T;
              d?: T;
              id?: T;
            };
      };
  cases?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        note?:
          | T
          | {
              icon?: T;
              bold?: T;
              text?: T;
            };
      };
  closing?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
        primaryLabel?: T;
        primaryHref?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careersIntro_select".
 */
export interface CareersIntroSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        ghost?: T;
        icon?: T;
        eyebrow?: T;
        title?: T;
        tagline?: T;
        intro?: T;
        primaryCtaLabel?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
        hud?:
          | T
          | {
              tag?: T;
              badge?: T;
              foot?: T;
              rows?:
                | T
                | {
                    icon?: T;
                    t?: T;
                    d?: T;
                    id?: T;
                  };
            };
      };
  why?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        items?:
          | T
          | {
              icon?: T;
              code?: T;
              t?: T;
              d?: T;
              id?: T;
            };
      };
  roles?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        note?:
          | T
          | {
              icon?: T;
              bold?: T;
              text?: T;
            };
      };
  closing?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
        primaryLabel?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resourcesOverview_select".
 */
export interface ResourcesOverviewSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        eyebrowIcon?: T;
        ghost?: T;
        title?: T;
        sub?: T;
        jump?:
          | T
          | {
              icon?: T;
              label?: T;
              href?: T;
              id?: T;
            };
      };
  tools?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        items?:
          | T
          | {
              icon?: T;
              tag?: T;
              title?: T;
              description?: T;
              href?: T;
              id?: T;
            };
      };
  library?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              href?: T;
              id?: T;
            };
      };
  closing?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "standardsIdentifierPage_select".
 */
export interface StandardsIdentifierPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        eyebrowIcon?: T;
        ghost?: T;
        title?: T;
        sub1?: T;
        sub2?: T;
        primaryCtaLabel?: T;
        primaryCtaHref?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
      };
  tool?:
    | T
    | {
        name?: T;
        sub?: T;
        badge?: T;
        selectors?:
          | T
          | {
              step?: T;
              label?: T;
              options?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
            };
        submitLabel?: T;
        submitNote?: T;
        resultLabel?: T;
        resultPreviewLabel?: T;
        roadmap?:
          | T
          | {
              code?: T;
              pill?: T;
              meta?: T;
              id?: T;
            };
        veilText?: T;
      };
  frameworks?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              codes?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  howItWorks?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        steps?:
          | T
          | {
              number?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  closing?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "safetyChatPage_select".
 */
export interface SafetyChatPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        eyebrowIcon?: T;
        ghost?: T;
        title?: T;
        sub?: T;
        note?: T;
        primaryCtaLabel?: T;
        primaryCtaHref?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
      };
  panel?:
    | T
    | {
        name?: T;
        status?: T;
        tag?: T;
        thread?:
          | T
          | {
              who?: T;
              text?: T;
              id?: T;
            };
        suggestions?:
          | T
          | {
              label?: T;
              id?: T;
            };
        placeholder?: T;
        lockText?: T;
        lockCtaLabel?: T;
        lockCtaHref?: T;
      };
  closing?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}